import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/common/navbar";
import ThemeProvider from "@/lib/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-roboto antialiased`}>
        <ThemeProvider>
          <div className="w-full h-screen flex flex-col gap-2">
            <Navbar />
            <div className="w-full flex-1">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
